# Generated by Django 2.1.5 on 2019-02-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('message', models.TextField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
